### ISSUE TITLE
how to use pkg module convert to execrable file(.exe)

### ISSUE THREAD

**Issue by AgileTerence** [chuckfairy/node-webcam#36]
Hi,
After I run the .exe file from node-webcam js converted to .exe through pkg module,  it is always getting an error message. Does anyone have any idea?

-------------------------------------Error Message-----------------------------------
Looking for the cameras...
Error: Command failed: "E:\snapshot\Agile_PeopleCounting\node_modules\node-webcam\src\bindings\CommandCam\Commandcam.exe" /devlist
�t�Χ䤣����w����|�C

    at ChildProcess.exithandler (child_process.js:281:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)

**Comment by kybarg** [comment]
@AgileTerence have you inlcued `node_modules\node-webcam\src\bindings\CommandCam\Commandcam.exe` as an asset?
